# Generated by Django 4.2 on 2024-11-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo_id', models.IntegerField(verbose_name='ID del Vehículo')),
                ('tipo_documento', models.CharField(choices=[('SOAT', 'SOAT'), ('Tecnomecanica', 'Tecnomecánica'), ('Poliza', 'Póliza')], max_length=20, verbose_name='Tipo de Documento')),
                ('fecha_expedicion', models.DateField(verbose_name='Fecha de Expedición')),
                ('fecha_expiracion', models.DateField(verbose_name='Fecha de Expiración')),
                ('estado', models.CharField(choices=[('Vigente', 'Vigente'), ('Vencido', 'Vencido')], max_length=10, verbose_name='Estado del Documento')),
                ('vista_previa', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
            options={
                'unique_together': {('vehiculo_id', 'tipo_documento')},
            },
        ),
    ]
