# Generated by Django 4.2 on 2024-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_talonario', models.CharField(max_length=6)),
                ('mes_a_pagar', models.CharField(choices=[('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre')], max_length=10)),
                ('fecha_de_pago', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento_pago', models.DateField(editable=False)),
                ('multas', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('estudiante_id', models.IntegerField()),
                ('user_id', models.IntegerField(editable=False)),
                ('estado_pago', models.BooleanField(default=False)),
                ('pago_multas', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('user_id', 'numero_talonario'), ('estudiante_id', 'mes_a_pagar')},
            },
        ),
    ]
