# Generated by Django 4.2 on 2024-11-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pago',
            unique_together=set(),
        ),
    ]
