version: '3.8'

services:
  instituciones:
    build:
      context: ./instituciones
      dockerfile: Dockerfile
    container_name: instituciones
    ports:
      - "8001:8001"
    networks:
      - backend
    depends_on:
      - db_institucion
    volumes:
      - ./instituciones:/app  # Volume asociado al WORKDIR del Dockerfile

  rutas:
    build:
      context: ./rutas
      dockerfile: Dockerfile
    container_name: rutas
    ports:
      - "8002:8002"
    networks:
      - backend
    depends_on:
      - instituciones
      - db_ruta
      - vehiculos
    volumes:
      - ./rutas:/app  # Volume asociado al WORKDIR del Dockerfile

  gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8003:8003"
    networks:
      - backend
    depends_on:
      - autenticacion
      - db_gateway
      - instituciones
      - rutas
  
  autenticacion:
    build:
      context: ./autenticacion
      dockerfile: Dockerfile
    container_name: autenticacion
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db_autenticacion
    volumes:
      - ./autenticacion:/app  # Volume asociado al WORKDIR del Dockerfile

  estudiantes:
    build:
      context: ./estudiantes
      dockerfile: Dockerfile
    container_name: estudiantes
    ports:
      - "8004:8004"
    networks:
      - backend
    depends_on:
      - db_autenticacion
      - db_estudiante
      - rutas
      - instituciones
    volumes:
      - ./estudiantes:/app  # Volume asociado al WORKDIR del Dockerfile

  conductores:
    build:
      context: ./conductores
      dockerfile: Dockerfile
    container_name: conductores
    ports:
      - "8005:8005"
    networks:
      - backend
    depends_on:
      - db_autenticacion
      - db_conductor
      - redis
    volumes:
      - ./conductores:/app  # Volume asociado al WORKDIR del Dockerfile

  conductores_worker:
    build:
      context: ./conductores
      dockerfile: Dockerfile
    container_name: conductores_worker
    command: celery -A conductores_service worker -l info
    networks:
      - backend
    depends_on:
      - conductores
      - redis
    volumes:
      - ./conductores:/app  # Volume asociado al WORKDIR del Dockerfile
    working_dir: /app/conductores_service
  
  conductores_beat:
    build:
      context: ./conductores
      dockerfile: Dockerfile
    container_name: conductores_beat
    command: celery -A conductores_service beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    networks:
      - backend
    depends_on:
      - conductores
      - redis
    volumes:
      - ./conductores:/app  # Volume asociado al WORKDIR del Dockerfile
    working_dir: /app/conductores_service
  

  vehiculos:
      build:
        context: ./vehiculos
        dockerfile: Dockerfile
      container_name: vehiculos
      ports:
        - "8006:8006"
      networks:
        - backend
      depends_on:
        - db_autenticacion
        - db_vehiculo
      volumes:
        - ./vehiculos:/app  # Volume asociado al WORKDIR del Dockerfile

  documentos:
      build:
        context: ./documentos_vehiculos
        dockerfile: Dockerfile
      container_name: documentos
      ports:
        - "8008:8008"
      networks:
        - backend
      depends_on:
        - db_autenticacion
        - db_documentos
      volumes:
        - ./documentos_vehiculos:/app  # Volume asociado al WORKDIR del Dockerfile
  
  documentos_worker:
    build:
      context: ./documentos_vehiculos
      dockerfile: Dockerfile
    container_name: documentos_worker
    command: sh -c "wait-for-it.sh rutas:8002 -t 60 -- celery -A documentos_service worker -l info"
    networks:
      - backend
    depends_on:
      - documentos
      - redis
      - rutas
    volumes:
      - ./documentos_vehiculos:/app  # Volume asociado al WORKDIR del Dockerfile
    working_dir: /app/documentos_service
    environment:
      - SERVICE_EMAIL=service_account
      - SERVICE_PASSWORD=Parada2023@

  documentos_beat:
    build:
      context: ./documentos_vehiculos
      dockerfile: Dockerfile
    container_name: documentos_beat
    command: celery -A documentos_service beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    networks:
      - backend
    depends_on:
      - documentos
      - redis
    volumes:
      - ./documentos_vehiculos:/app  # Volume asociado al WORKDIR del Dockerfile
    working_dir: /app/documentos_service

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  db_institucion:
    image: postgres:13
    volumes:
      - postgres_data_instituciones:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=instituciones
      - POSTGRES_USER=brian
      - POSTGRES_PASSWORD=parada2023
    ports:
      - "5432:5432"
    networks:
      - backend

  db_ruta:
    image: postgres:13
    volumes:
      - postgres_data_ruta:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ruta
      - POSTGRES_USER=brian
      - POSTGRES_PASSWORD=parada2023
    ports:
      - "5433:5432"
    networks:
      - backend

  db_gateway:
    image: postgres:13
    volumes:
      - postgres_data_gateway:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gateway
      - POSTGRES_USER=brian
      - POSTGRES_PASSWORD=parada2023
    ports:
      - "5434:5432"
    networks:
      - backend

  db_autenticacion:
    image: postgres:13
    volumes:
      - postgres_data_autenticacion:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=autenticacion
      - POSTGRES_USER=brian
      - POSTGRES_PASSWORD=parada2023
    ports:
      - "5435:5432"
    networks:
      - backend

  
  db_estudiante:
    image: postgres:13
    volumes:
      - postgres_data_estudiante:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=estudiante
      - POSTGRES_USER=brian
      - POSTGRES_PASSWORD=parada2023
    ports:
      - "5436:5432"
    networks:
      - backend

  db_conductor:
    image: postgres:13
    volumes:
      - postgres_data_conductor:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=conductor
      - POSTGRES_USER=brian
      - POSTGRES_PASSWORD=parada2023
    ports:
      - "5437:5432"
    networks:
      - backend

  db_vehiculo:
      image: postgres:13
      volumes:
        - postgres_data_vehiculo:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=vehiculo
        - POSTGRES_USER=brian
        - POSTGRES_PASSWORD=parada2023
      ports:
        - "5438:5432"
      networks:
        - backend

  db_documentos:
      image: postgres:13
      volumes:
        - postgres_data_documentos:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=documento
        - POSTGRES_USER=brian
        - POSTGRES_PASSWORD=parada2023
      ports:
        - "5439:5432"
      networks:
        - backend
    
networks:
  backend:
    driver: bridge

volumes:
  postgres_data_instituciones:
  postgres_data_ruta:
  postgres_data_gateway: 
  postgres_data_autenticacion:
  postgres_data_estudiante:
  postgres_data_conductor:
  postgres_data_vehiculo:
  postgres_data_redis:
  postgres_data_documentos:
