# Generated by Django 4.2 on 2024-10-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Ruta')),
                ('ruta_movil', models.IntegerField(unique=True, verbose_name='Numero Movil')),
                ('institucion_id', models.IntegerField(verbose_name='ID de institucion')),
                ('activa', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
