# Generated by Django 4.2 on 2024-11-16 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo_placa', models.CharField(max_length=10, verbose_name='Placa del Vehículo')),
                ('vehiculo_marca', models.CharField(max_length=50, verbose_name='Marca del Vehículo')),
                ('vehiculo_modelo', models.IntegerField(verbose_name='Modelo del Vehículo')),
                ('vehiculo_imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('vehiculo_capacidad', models.PositiveIntegerField(verbose_name='Capacidad del Vehículo')),
                ('ruta_id', models.IntegerField(verbose_name='ID de la Ruta')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('user_id', models.IntegerField()),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitora', to='api.vehiculo')),
            ],
        ),
    ]
