# Generated by Django 4.2 on 2024-11-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_monitora_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitora',
            name='telefono',
            field=models.CharField(verbose_name='Teléfono'),
        ),
    ]
