# Generated by Django 4.2 on 2024-11-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_monitora_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitora',
            name='telefono',
            field=models.CharField(max_length=10, unique=True, verbose_name='Teléfono'),
        ),
    ]
