# Generated by Django 4.2 on 2024-10-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Conductor')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido del Conductor')),
                ('edad', models.IntegerField(verbose_name='Edad del Conductor')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono del Conductor')),
                ('foto', models.ImageField(upload_to='logos/', verbose_name='Foto del Conductor')),
                ('fecha_exp', models.DateField(verbose_name='Fecha de Expedición de Licencia')),
                ('fecha_expiracion', models.DateField(verbose_name='Fecha de Expiración de Licencia')),
                ('licencia_activa', models.BooleanField(default=True, verbose_name='Licencia Activa')),
            ],
        ),
    ]
